baseURL = "https://bytesbyck.com"
languageCode = "en-us"
title = "Chaitanya's Blog"
theme = "PaperMod"
enableRobotsTXT = true
description = "The place on the web where I share blog posts filled with my knowledge. ğŸ“š"

[languages.en]
  languageName = "English"
  weight = 1

  [languages.en.taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

  [[languages.en.menu.main]]
    name = "Archive"
    url = "archives"
    weight = 5

  [[languages.en.menu.main]]
    name = "Search"
    url = "search/"
    weight = 10

  [[languages.en.menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 10

[params]
  author = "Chaitanya"
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  
  [params.homeInfoParams]
    Title = "ğŸŒŸ Hi there! ğŸ‘‹"
    Content = "Welcome to my blog! ğŸŒ Dive into my thoughts, insightful tips, and so much more. Enjoy your stay, and feel free to explore! ğŸ˜Š"

  [params.assets]
    favicon = "/assets/favicon.ico"
    favicon16x16 = "/assets/favicon-16x16.png"
    favicon32x32 = "/assets/favicon-32x32.png"
    apple_touch_icon = "/assets/apple-touch-icon.png"
    safari_pinned_tab = "/assets/favicon.ico"
  

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/chaitualluri"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/chaitanya-kumar-alluri-5a70203b/"

[[params.socialIcons]]
  name = "rss"
  url = "feed.xml"

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

  # SEO Metadata
  siteName = "Chaitanya's Blog"
  keywords = ["blog", "technology", "coding", "development", "knowledge sharing", "Stock Market", "Finance"]
  canonifyUrls = true

[outputs]
  home = ["HTML", "RSS", "JSON"]